apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: customer006
type: Opaque
stringData:
  password: REPLACE_ME
  root-password: REPLACE_ME

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: customer006
type: Opaque
stringData:
  auth-key: REPLACE_ME
  secure-auth-key: REPLACE_ME
  logged-in-key: REPLACE_ME
  nonce-key: REPLACE_ME
  auth-salt: REPLACE_ME
  secure-auth-salt: REPLACE_ME
  logged-in-salt: REPLACE_ME
  nonce-salt: REPLACE_ME
