# values.yaml - Helm configuration file for the WordPress stack

cluster:
  customerName: "customer006"
  workerNode: "worker03"

replicaCount: 1

database:
  service:
    user: "wpuser"
    name: "wordpress"
  secret:
    create: false
    name: "mysql-secrets"
    data:
      password: "CHANGE_ME_BASE64_DB_PASSWORD"
      rootPassword: "CHANGE_ME_BASE64_DB_ROOT_PASSWORD"


wordpress:
  version: "7.0.0"
  secret:
    name: "wordpress-secrets"
    keys:
      authKey: "auth-key"
      secureAuthKey: "secure-auth-key"
      loggedInKey: "logged-in-key"
      nonceKey: "nonce-key"
      authSalt: "auth-salt"
      secureAuthSalt: "secure-auth-salt"
      loggedInSalt: "logged-in-salt"
      nonceSalt: "nonce-salt"

network:
  domain: "customer006.web-services.sytes.net"
  ingress:
    gatewayName: "public-gateway"
    sectionName: "https"
    namespace: "default"

monitoring:
  allowedMetricsIPs:
    - "192.168.51.96"
    - "192.168.0.145"

# Resource Limits
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 95
  targetMemoryUtilizationPercentage: 95

# Specific resource requests/limits (can be used in templates if needed)
resources:
  wordpress:
    cpuRequests: "50m"
    cpuLimits: "100m"
    memoryRequests: "192Mi"
    memoryLimits: "256Mi"
  mysql:
    cpuRequests: "50m"
    cpuLimits: "100m"
    memoryRequests: "464Mi"
    memoryLimits: "966Mi"

# Additional configuration variables
serverAdminEmail: "CHANGE_ME_SERVER_ADMIN_EMAIL"
